// <auto-generated />
using System;
using ChatJaffApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatJaffApp.Server.Migrations.JaffDb
{
    [DbContext(typeof(JaffDbContext))]
    partial class JaffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("ChatJaffApp.Server.ChatRoom.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Encrypted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChatRooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d728ec3-1f6b-4170-8827-bc064ae25a41"),
                            ChatName = "Chat 1",
                            Creator = "Filip",
                            Encrypted = false
                        },
                        new
                        {
                            Id = new Guid("1fcf8eb7-2658-47e2-aff5-c396ae65de92"),
                            ChatName = "Chat 2",
                            Creator = "Baronen",
                            Encrypted = false
                        });
                });

            modelBuilder.Entity("ChatJaffApp.Server.ChatRoom.Models.ChatMember", b =>
                {
                    b.Property<Guid?>("ChatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMembers");

                    b.HasData(
                        new
                        {
                            ChatId = new Guid("5d728ec3-1f6b-4170-8827-bc064ae25a41"),
                            UserId = new Guid("9f7e8005-873a-489d-b569-afb17a58b051")
                        },
                        new
                        {
                            ChatId = new Guid("5d728ec3-1f6b-4170-8827-bc064ae25a41"),
                            UserId = new Guid("c4423797-979c-4a72-a7f8-53499aab5469")
                        },
                        new
                        {
                            ChatId = new Guid("5d728ec3-1f6b-4170-8827-bc064ae25a41"),
                            UserId = new Guid("28e44613-4ace-474b-965f-e589e72aaf46")
                        },
                        new
                        {
                            ChatId = new Guid("1fcf8eb7-2658-47e2-aff5-c396ae65de92"),
                            UserId = new Guid("e36d119f-f8e3-4bd1-a3f1-0845f8cbe529")
                        },
                        new
                        {
                            ChatId = new Guid("1fcf8eb7-2658-47e2-aff5-c396ae65de92"),
                            UserId = new Guid("28e44613-4ace-474b-965f-e589e72aaf46")
                        },
                        new
                        {
                            ChatId = new Guid("1fcf8eb7-2658-47e2-aff5-c396ae65de92"),
                            UserId = new Guid("95a471ee-e8a7-44d4-bb13-c5090fb1a5ce")
                        });
                });

            modelBuilder.Entity("ChatJaffApp.Server.Data.Models.ChatKey", b =>
                {
                    b.Property<Guid>("ChatRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChatRoomId");

                    b.ToTable("ChatKeys");
                });

            modelBuilder.Entity("ChatJaffApp.Server.Data.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ceaa7ab-1c67-4ed4-a86a-6bd01df6c310"),
                            UserName = "member1"
                        },
                        new
                        {
                            Id = new Guid("b8381d75-d110-42f9-85e5-9c92a062fbc8"),
                            UserName = "member2"
                        },
                        new
                        {
                            Id = new Guid("9f7e8005-873a-489d-b569-afb17a58b051"),
                            UserName = "Batman42"
                        },
                        new
                        {
                            Id = new Guid("c4423797-979c-4a72-a7f8-53499aab5469"),
                            UserName = "Catwoman"
                        },
                        new
                        {
                            Id = new Guid("28e44613-4ace-474b-965f-e589e72aaf46"),
                            UserName = "Randy"
                        },
                        new
                        {
                            Id = new Guid("e36d119f-f8e3-4bd1-a3f1-0845f8cbe529"),
                            UserName = "Bandy"
                        },
                        new
                        {
                            Id = new Guid("95a471ee-e8a7-44d4-bb13-c5090fb1a5ce"),
                            UserName = "Silvio"
                        });
                });

            modelBuilder.Entity("ChatJaffApp.Server.Data.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Sent")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abda0517-7354-49fc-9239-8e350b42fb9d"),
                            ChatId = new Guid("5d728ec3-1f6b-4170-8827-bc064ae25a41"),
                            Content = " Cathy, Meet me at the batcave girrl",
                            Sent = new DateTime(2023, 2, 8, 10, 32, 26, 261, DateTimeKind.Utc).AddTicks(8919),
                            UserId = new Guid("9f7e8005-873a-489d-b569-afb17a58b051")
                        },
                        new
                        {
                            Id = new Guid("439f95cc-b2d6-4375-9281-6a5c65ba3806"),
                            ChatId = new Guid("5d728ec3-1f6b-4170-8827-bc064ae25a41"),
                            Content = " Sure thang battyboy",
                            Sent = new DateTime(2023, 2, 8, 10, 32, 26, 261, DateTimeKind.Utc).AddTicks(8926),
                            UserId = new Guid("c4423797-979c-4a72-a7f8-53499aab5469")
                        });
                });

            modelBuilder.Entity("ChatJaffApp.Server.ChatRoom.Models.ChatMember", b =>
                {
                    b.HasOne("ChatJaffApp.Server.ChatRoom.Models.Chat", "Chat")
                        .WithMany("ChatMembers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatJaffApp.Server.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ChatJaffApp.Server.Data.Models.Message", b =>
                {
                    b.HasOne("ChatJaffApp.Server.ChatRoom.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatJaffApp.Server.Data.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ChatJaffApp.Server.ChatRoom.Models.Chat", b =>
                {
                    b.Navigation("ChatMembers");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
