name: dotnet build and test

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: move dir and run npm
        run: cd ChatJaffApp && npm install
      - name: build dotnet
        run: dotnet build ChatJaffApp
      - name: Test
        run: cd ChatJaffApp && npm run test-cypress
