name: dotnet build and test

on:
  push:
    branches: [ "hotfix/gettesttopassongithub" ]
  pull_request:
    branches: [ "hotfix/gettesttopassongithub" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: build dotnet
      run: dotnet build ChatJaffApp/ChatJaffApp.Server/ChatJaffApp.Server.csproj
    - name: install npm
      run: npm install .
    - name: Test
      run: npm run test-cypress
